fixtures:
  # use the forge modules so we can easily pin to a specific version
  forge_modules:
    firewall: "puppetlabs/firewall"
    git: "puppetlabs/git"
    java: "puppetlabs/java"
    mysql: "puppetlabs/mysql"
    stdlib: "puppetlabs/stdlib"
#  repositories:
#    firewall: "git://github.com/puppetlabs/puppetlabs-firewall.git"
#    git: "git://github.com/puppetlabs/puppetlabs-git.git"
#    java: "git://github.com/puppetlabs/puppetlabs-java.git"
#    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
#    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    gerrit: "#{source_dir}"
