fixtures:
  # use the forge modules so we can easily pin to a specific version
  forge_modules:
    firewall: "puppetlabs/firewall"
    git: "puppetlabs/git"
    java: "puppetlabs/java"
    mysql: "puppetlabs/mysql"
    stdlib: "puppetlabs/stdlib"
    wget: "maestrodev/wget"
  symlinks:
    gerrit: "#{source_dir}"
